import { useRef, useState } from "react";
import { ArrowLeft, Paperclip, X } from "lucide-react";
import { AppShell } from "../components/AppShell";
import { api } from "../lib/api";
import { useRouter } from "../lib/router";
import { useSession } from "../session";
import "../styles/create-post.css";

const blank = { title: "", content: "", category: "Технологии", tags: "" };
export function CreatePostPage() {
  const { user } = useSession(); const { navigate } = useRouter(); const fileInput = useRef(null);
  const [form, setForm] = useState(blank); const [files, setFiles] = useState([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (!user) { navigate("/login"); return null; }
  const update = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const addFiles = (selected) => { const next = [...files, ...Array.from(selected)].slice(0, 4); if (next.filter((file) => file.type.startsWith("video/")).length > 1) return setError("К публикации можно добавить только одно видео."); if (next.some((file) => file.size > (file.type.startsWith("video/") ? 100 : 10) * 1024 * 1024)) return setError("Один из файлов превышает допустимый размер."); setError(""); setFiles(next); };
  const payload = async () => { const media = await Promise.all(files.map((file) => api.uploadMedia(file))); return { title: form.title.trim(), content: form.content.trim(), category: form.category, tags: form.tags.split(",").map((tag) => tag.trim()).filter(Boolean), media_ids: media.map((item) => item.id) }; };
  const submit = async (draft) => { setBusy(true); setError(""); try { const data = await payload(); const result = draft ? await api.createDraft(data) : await api.createPost(data); navigate(draft ? "/drafts" : `/posts/${result.id}`); } catch (cause) { setError(cause.message || "Не удалось сохранить публикацию"); } finally { setBusy(false); } };
  return <AppShell title="Создать"><section className="create-page"><button className="back-link button-link" onClick={() => navigate("/")}><ArrowLeft size={17} /> Отмена</button><h1>Новая публикация</h1><p>Поделитесь идеей с сообществом</p><form className="create-form" onSubmit={(event) => { event.preventDefault(); submit(false); }}><label>Заголовок <small>обязательно</small><input value={form.title} onChange={update("title")} maxLength="200" required placeholder="О чём ваша публикация?" /></label><label>Текст <small>обязательно</small><textarea value={form.content} onChange={update("content")} maxLength="10000" required placeholder="Расскажите больше…" /></label><div className="create-grid"><label>Категория<select value={form.category} onChange={update("category")}><option>Технологии</option><option>Дизайн</option><option>Культура</option><option>Идеи</option></select></label><label>Теги <small>через запятую</small><input value={form.tags} onChange={update("tags")} maxLength="300" placeholder="design, product" /></label></div><div className="attachments"><header><div><b>Вложения</b><small>До 4 файлов, максимум одно видео</small></div><button type="button" className="outline-button" onClick={() => fileInput.current.click()}><Paperclip size={18} /> Добавить файл</button></header><input ref={fileInput} className="visually-hidden" type="file" accept="image/*,video/*" multiple onChange={(event) => addFiles(event.target.files)} />{files.length > 0 && <div className="file-list">{files.map((file, index) => <div className="file-chip" key={`${file.name}-${index}`}><span>{file.type.startsWith("video/") ? "Видео" : "Фото"}</span><b>{file.name}</b><button type="button" onClick={() => setFiles((items) => items.filter((_, fileIndex) => fileIndex !== index))} aria-label="Удалить файл"><X size={17} /></button></div>)}</div>}</div>{error && <div className="form-error" role="alert">{error}</div>}<footer><button type="button" className="outline-button" disabled={busy} onClick={() => submit(true)}>Сохранить черновик</button><button className="primary" disabled={busy}>{busy ? "Публикуем…" : "Опубликовать"}</button></footer></form></section></AppShell>;
}
